FROM ros:jazzy

# Install basic tools and ROS dependencies
RUN sudo apt update -y && sudo apt install -y \
    python3-pip \
    python3-opencv \
    python3-numpy \
    ros-jazzy-cv-bridge \
    wget \
    usbutils \
    ros-jazzy-turtlesim* \
    ros-jazzy-rqt-graph \
    ros-jazzy-example-interfaces \
    && rm -rf /var/lib/apt/lists/*